version: "3.9"
services:
    app:
        build: ./docker/php
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    web:
        image: nginx:1.20
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/html
        depends_on:
            - app
    db:
        build: ./docker/mysql
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8888:80
        depends_on:
            - db
